<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add email' => '',
    'Are you sure you want to delete this item?' => '',
    'Avatar' => '',
    'Create' => '',
    'Created At' => '',
    'Delete' => '',
    'Description' => '',
    'Disable' => '',
    'Email' => '',
    'Empty' => '',
    'Enable' => '',
    'End' => '',
    'End:' => '',
    'Event ID' => '',
    'Event search' => '',
    'Export event to Google Calendar' => '',
    'Facebook ID' => '',
    'Find the event you are interested in:' => '',
    'Google ID' => '',
    'ID' => '',
    'Lat' => '',
    'Lng' => '',
    'My Events' => '',
    'Name' => '',
    'Owner' => '',
    'Page not found' => '',
    'Photos' => '',
    'Place Name' => '',
    'Private' => '',
    'Protected' => '',
    'Public' => '',
    'Reset' => '',
    'Save' => '',
    'Search' => '',
    'Start' => '',
    'Start time must be less than end time' => '',
    'Start:' => '',
    'Status' => '',
    'Subscribe' => '',
    'This site for offline events' => '',
    'Twitter ID' => '',
    'Unsubscribe' => '',
    'Update' => '',
    'Update {modelClass}: ' => '',
    'Updated At' => '',
    'User ID' => '',
    'Visible' => '',
    'Welcome' => '',
    'this link.' => '',
    'About' => 'Про Нас',
    'Browse' => 'Огляд',
    'Create Event' => 'Створити подію',
    'Events' => 'Події',
    'Home' => 'Головна',
    'Login' => 'Вхід',
    'Logout ({user})' => 'Вихід ({user})',
    'N/A' => 'Не задано',
    'Profile' => 'Профіль',
    'UAH' => 'грн.',
    'Users' => 'Користувачі',
    'View' => 'Переглянути',
];
