<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Settings' => 'Налаштування',
    'About' => 'Про Нас',
    'Administration' => 'Адміністування',
    'Browse' => 'Огляд',
    'Buy' => 'Купити',
    'Cart' => 'Корзина',
    'Catalog' => 'Каталог',
    'Categories' => 'Категорії',
    'Contact' => 'Контакти',
    'Hide' => 'Згорнути',
    'Home' => 'Головна',
    'Login' => 'Вхід',
    'Logout ({user})' => 'Вихід ({user})',
    'N/A' => 'Не задано',
    'Orders' => 'Замовлення',
    'Price: ' => 'Ціна: ',
    'Products' => 'Товари',
    'Products of category {category}:' => 'Товари категорії {category}:',
    'Products of vendor {vendor}:' => 'Товари виробника {vendor}:',
    'Read more' => 'Читати більше',
    'Subcategories:' => 'Категорії: ',
    'The requested page does not exist.' => 'Ця сторінка не доступна',
    'UAH' => 'грн.',
    'Users' => 'Користувачі',
    'Vendor: ' => 'Виробник: ',
    'Vendors' => 'Виробники',
    'View' => 'Переглянути',
    'pcs.' => 'шт.',
    'Events' => 'Події',
    'Profile' => 'Профіль',
    'Create Event' => 'Створити подію',
];
